Twitter/accounts/urls.py
from django.urls import path
from .views import *
from django.urls import reverse

app_name = 'accounts'
urlpatterns = [
    path('login/', login_view, name='login'),
    path('register/', register_view, name='register'),
    path('logout/', logout_view, name='logout'),


]

Twitter/icetin/urls.py
from django.contrib import admin
from django.urls import path, include
from home.views import home_view
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_view, name='home'),
    path('post/',include('post.urls')),
    path('accounts/',include('accounts.urls')),


]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Twitter/post/urls.py
from django.urls import path
from .views import *
from django.urls import reverse

app_name = 'post'
urlpatterns = [
    path('index/', post_index, name='index'),
    path('create/', post_create, name='create'),
    path('<slug>/', post_detail, name='detail'),
    path('<slug>/update/', post_update, name='update'),
    path('<slug>/delete/', post_delete, name='delete'),

]

Twitter/home/models.py
from django.db import models

# Create your models here.

Twitter/home/views.py
from django.shortcuts import render

import sys
import os

from post.models import Post

# Create your views here.



def home_view(request):
    posts_list = Post.objects.all()
    print(len(posts_list))
    if request.user.is_authenticated:

        context = {
            'isim':request.user.get_full_name,
        }
    else:
        context = {
            'isim': 'Misafir',
        }
    return render(request, 'home.html',{"context":context,"posts":posts_list})

Twitter/templates/base.html
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8", name="viewport" content="width=device-width, inital-scale=1">
    <title>{% block title %}Twitter Analiz{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">







</head>
<body>
    {% include 'header.html' %}

    {% include 'messages.html' %}

    {% block body %}

    {% endblock %}

    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

Twitter/templates/header.html
<nav class="navbar navbar-expand-lg navbar-light bg-primary">
  <a class="navbar-brand" href="{% url 'home' %}">Twitter Analiz</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>



  <div class="collapse navbar-collapse" id="navbarSupportedContent">

    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link " href="{% url 'home' %}">Home<span class="sr-only">(current)</span></a>
      </li>


    {% if not request.user.is_authenticated %}


    <li class="nav-item">
        <a class="nav-link" href="{% url 'accounts:register' %}">Üye Ol</a>
      </li>
    <li class="nav-item">
        <a class="nav-link" href="{% url 'accounts:login' %}">Giriş</a>
      </li>
                  <li class="nav-item">
            <a class="nav-link" href="">{{ isim }}</a>
          </li>
    {% else %}
        <li class="nav-item">
        <a class="nav-link" href="{% url 'accounts:logout' %}">Çıkış</a>
      </li>

    {% endif %}

        {% if request.user.is_authenticated %}

          <li class="nav-item">
            <a class="nav-link" href="{% url 'post:create' %}">Yazı ekle</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="">{{ isim }}</a>
          </li>

        {% endif %}

{#      <li class="nav-item dropdown">#}
{#        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">#}
{#          Dropdown#}
{#        </a>#}
{#        <div class="dropdown-menu" aria-labelledby="navbarDropdown">#}
{#          <a class="dropdown-item" href="#">Action</a>#}
{#          <a class="dropdown-item" href="#">Another action</a>#}
{#          <div class="dropdown-divider"></div>#}
{#          <a class="dropdown-item" href="#">Something else here</a>#}
{#        </div>#}
{#      </li>#}
{#      <li class="nav-item">#}
{#        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>#}
{#      </li>#}
    </ul>


  </div>
</nav>

Twitter/templates/home.html
{% extends 'base.html'%}
{% load static %}
{% block title %} Anasayfa - {{ block.super }}{% endblock %}
{% block body %}

<html lang="en">




    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">




    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">


    <title>RecipeList - Stylish Magazine Blog Template</title>
    <meta name="keywords" content="">
    <meta name="description" content="">
    <meta name="author" content="">


    <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}" type="image/x-icon" />
    <link rel="apple-touch-icon" href="{% static 'images/apple-touch-icon.png' %}">


    <link href="https://fonts.googleapis.com/css?family=Montserrat:300,400,400i,500,600,700,800,900" rel="stylesheet">


    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">


    <link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet">


    <link href="{% static 'style.css' %}" rel="stylesheet">


    <link href="{% static 'css/responsive.css' %}" rel="stylesheet">


    <link href="{% static 'css/colors.css' %}" rel="stylesheet">


      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>





<body>


<div class="banner">
    <img src="{% static 'images/twiter.jpg' %}"width="1000px">
</div>




    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/tether.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/custom.js' %}"></script>

</body>
</html>
{% endblock %}

Twitter/templates/messages.html
{% if messages %}

    {% for message in messages %}
        <div class="alert alert-success alert-dismissible fade show" role="alert">
          <strong>{{ message }}!</strong>
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>

    {% endfor %}

{% endif %}